---
- name: Install Apache
  hosts: all
  become: yes



  tasks:
  - name: install Apache
    apt:
      name: apache2
      state: present 
  
  - mame: Start Apache
    service:
      name: httpd
      state: started
