---
- name: Install Apache and upload web site
  hosts: all
  become: yes

  vars:
    source_file: index.html
    dst_file: /var/www/html 



  tasks:
  - name: install Apache
    apt:
      name: apache2
      state: present
  
  - name: Start Apache
    service:
      name: apache2
      state: started
  - name: example copying file with owner and permissions
    ansible.builtin.template
       src: "{{source_file}}"
       dest: "{{dst_file}}"
       notify:
        - Restart apache2
  
  handlers:
  - name: Restart apache2
    service:
      name: apache2
      state: restarted