---
- name: Install Apache and upload web site !!!!!!!!!
  hosts: all
  become: yes

  vars:
    source_file: index.html
    dst_file: /var/www/html

  tasks:
    - name: check linux version
      ansible.builtin.debug:
        var: ansible_os_family

    - name: Install apache httpd (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_os_family == "Ubuntu"

    - name: Install the latest version of Apache
      ansible.builtin.dnf:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Start Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: example copying file with owner and permissions
      ansible.builtin.template:
        src: "{{source_file}}"
        dest: "{{dst_file}}"
      notify:
        - Restart apache2

  handlers:
    - name: Restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
