---
- name: Install Apache and upload web site
  hosts: all
  become: yes

  vars:
    source_file: index.html
    dst_file: /var/www/html 


  tasks:
  - name: check linux version
    debug:
      var: ansible_os_family

  - name: install Apache for ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Install the latest version of Apache
    ansible.builtin.dnf:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"
  
  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_os_family == "Debian"
      
  - name: example copying file with owner and permissions
    ansible.builtin.template:
       src: "{{source_file}}"
       dest: "{{dst_file}}"
    notify:
       - Restart apache2
  
  handlers:
    - name: Restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
      when: ansible_os_family == "Debian"