---
- name: Install Apache and upload web site
  hosts: all
  become: yes

  vars:
    source_file: index.html
    dst_file: /var/www/html 


  tasks:
  - name: check linux version
    debug:
      var: ansible_os_family
  
  - name: Install apache  Debian
      ansible.builtin.apt:
      name: apache2
      state: present

  - name: example copying file with owner and permissions
      ansible.builtin.template:
      src: "{{source_file}}"
      dest: "{{dst_file}}"
      notify:
       - Restart apache2

  - name: Start Apache Debian
    service:
      name: apache2
      state: started
      enabled: yes
  when: ansible_os_family == "Debian"

  - name: Install the latest version of Apache RedHat
    ansible.builtin.dnf:
      name: httpd
      state: latest
  when: ansible_os_family == "RedHat"
      
  - name: example copying file with owner and permissions
    ansible.builtin.template:
       src: "{{source_file}}"
       dest: "{{dst_file}}"
  notify:
       - Restart apache2
  
  handlers:
    - name: Restart apache2
      ansible.builtin.service:
        name: apache2
        state: restarted